services:
    watchtower:
        image: containrrr/watchtower:latest
        container_name: watchtower
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=${TZ}
            - WATCHTOWER_CLEANUP=true
            - WATCHTOWER_INCLUDE_STOPPED=true
            - WATCHTOWER_REVIVE_STOPPED=false
            - WATCHTOWER_SCHEDULE=0 30 8 * * 1 # Every Monday at 8:30 AM
            - WATCHTOWER_NOTIFICATIONS=shoutrrr
            - WATCHTOWER_NOTIFICATION_URL=${WATCHTOWER_NOTIFICATION_URL}
        command:
            - audiobookshelf
            - prowlarr
            - radarr
            - sonarr
            - bazarr
            - flaresolverr
            - glance
            - jellyfin
            - jellyseerr
            - n8n
            - qbittorrent
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        network_mode: host
        restart: unless-stopped
